### ISSUE TITLE
themes: customize and create own themes

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#101]
Not sure what the best way is. For customization, perhaps a `.config` extension that overrides themes colors?

**Comment by vfosnar** [comment]
Custom themes (like external yaml config) is something I need, because as of now I have to maintain a fork of this program just to add my own colors.

Right now I can think of something like `--theme_file path/to/config.yaml` and with #623 in mind also `--theme_dark_file path/to/config_dark.yaml`.

I will look into how this could be implemented when I'll have some time.

**Comment by MariusAlbrecht** [comment]
I'd suggest using a predefined local file structure so that the user doesn't have to use paths (additionally another flag can be avoided)
imagine the following file structure in any default location (which could ofc be changed by adding a config somewhere which holds that location. Dont think thats necessary tho)
```
<some default location>
'- themes
   '- theme1.<someFileExtension>
   '- theme2.<someFileExtension
   '- theme3.<someFileExtension>
```
the names of the files could then be searched/indexed and passed by the user the same way they would pass the IDs (e.g. `--theme theme1` in this example)

File extensions could be anything but I'd actually suggest .ini bcs its so simple (just like the usecase). Just using .go files and not bothering with parsing would be the other option for me. I don't really see a reason to use any more complicated formats such as yml or json. At that point just use go directly.

**Comment by vfosnar** [comment]
Well, you can't use go files AFAIK because go is a compiled language. Also it makes sense to use `.ini`, I just forgot it exists.

About the location, think the use case of D2. For example I want to use it for my personal blog and I need to have my theme managed by a VCS. How could I do that while having a user-wide themes folder?

**Comment by MariusAlbrecht** [comment]
The remark about go makes sense. I dont really know go 😅.
To satisfy your usecase I see 2 options:
- require the user(/you) to do a symlink which links from the theme folder to your desired location (aka where the file is visible for the vsc)
- ontop of the theming folder also specify a way to put theme files in the working directory, so that the (rough) workflow would be
              (0. check for theme internally)
              1. check for theme file in working dir
              3. check for theme file in theme folder
              4. fail (rather fall back to default)

I also wanted to bring up the issue of fonts here. Seems to be almost the same thing of having to add them to the actual app which could create both licensing and usability issues. Afaict a mechanism for selecting different font (even internally) doesnt exist currently and would have to be created tho
Example to illustrate: I want to use a font which I have the license to, however the license doesnt permit me adding the font to the main repo. Now I have to either break the license (and cause potential trouble), not use the font at all or maintain a local fork (and re-build with every update)

also look at [spicetify](https://github.com/spicetify/spicetify-themes) for `.ini` themes

**Comment by vfosnar** [comment]
I think just adding another CLI argument is much easier than not forgetting that I have to symlink every time I clone a repository.

Yeah I think that more fonts / loading fonts dynamically should be supported, but as I use only sketch mode and the handwritten font looks nice this is kinda out of scope for me.

**Comment by FollieHiyuki** [comment]
Just my 2 cents:
- For theming, I like the idea of @MariusAlbrecht (putting theme files inside a `themes/` folder and they are then parsed by `d2`). Also, I'd suggest adding an option in the config file, e.g. `default_theme = <theme_name>` so `d2` knows which theme to use by default when none is specified in the CLI.
- For font style, I'd like `d2` to use the system Sans font by default. This has the benefit of `d2` not having to bundle any fonts on its own. The user can choose to use another font by either providing the font name (`d2` will search the font cache in their system to find the correct font to load) or pointing it to the `*.ttf` file directly.
