### ISSUE TITLE
syntax: classes

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#102]
classes should aggregate styles so you don't have to apply the same set of styles in a bunch of places

**Comment by orsinium** [comment]
+1 to the feature. My use case is that I use D2 for producing [event storming](https://en.wikipedia.org/wiki/Event_storming) diagram. Event storming, having its roots in the physical world of sticky notes, uses colors rather than shapes for denoting different kinds of elements. And the current solution with d2 to dolor elements is to explicitly add the style to each element.

**Comment by iAdanos** [comment]
+1 for this and https://github.com/terrastruct/d2/issues/133

Complex diagrams with different entity types are much better with styling, but currently every shape and container must be styled separately, which makes the code completely unreadable.

**Comment by alixander** [comment]
thanks for the bump @iAdanos. i'll do classes this week

**Comment by robertlagrant** [comment]
+1 to this from me as well - my use case is a sequence diagram where each span has the same customisations applied, and also each actor has a different colour for their spans.

**Comment by iAdanos** [comment]
> thanks for the bump @iAdanos. i'll do classes this week

@alixander, any updates?

**Comment by alixander** [comment]
@iAdanos unfortunately not. hopefully this weekend!
