### ISSUE TITLE
feat: root selector / Reference Root level

### ISSUE THREAD

**Issue by johannes-z** [terrastruct/d2#1075]
Similar to the `_` (reference parent), an option to reference the root level (for example as `~`) could be helpful. This would make it a little cleaner, if you have a lot of nested objects.

Example: https://play.d2lang.com/?script=SrRSqOZSUEjOyMxJ4arl4kqC8iEUTALBVNC1U4jXi9dL1IPIKCjUgrRxVaCZUwnhV-Ezp06vAsUUQAAAAP__&

```d2
a: {
  child
}

b: {
  c: {
    child

    child -> _._.a.child 
  }
}

x: {
  child
}

y: {
  z: {
    child

    child -> ~.x.child # ~ = root
  }
}
```

**Comment by alixander** [comment]
@johannes-z thank you for the suggestion! we've thought about this before, but ultimately decided not to allow it. the reason is because we will soon have imports, and "layers", where you can click into abstraction levels (e.g. https://github.com/terrastruct/d2/pull/966). If we had `~`, it would have to change depending on imports, and we don't want that type of unpredictability
