### ISSUE TITLE
Feature: circuit diagram

### ISSUE THREAD

**Issue by akshaybabloo** [terrastruct/d2#1244]
It will be good to have a way to create circuit diagrams using D2.

**Comment by alixander** [comment]
hey @akshaybabloo thank you for the suggestion! Do you have an example of what you mean?

**Comment by akshaybabloo** [comment]
@alixander Certainly. Consider the following example of a circuit diagram (make of Autodesk Fusion 365):

![temp](https://user-images.githubusercontent.com/7360286/234445833-5fea4dcb-da00-4f97-a626-2ef11a8b410a.jpg)

> The only difference between `US` and `NON-US` is how the resistor is denoted.

I tried to do this via D2, and this is what I got:

```d2
direction: right

classes: {
  resistor: {
    shape: rectangle
    height: 10
  }
}

9v -> 350k -> led -> 9v
350k.class: resistor
```

https://play.d2lang.com/?script=gkevlUIRKDi5uKCpwEqhmktBoSi1OLO4JL8IwlNQAIeClQJIT2Jeek4qWBASEVYKhgZcCgq1XLVcXJZlCrp2CsamBtkgOic1BURZlnGBRPTAFljBjeYCBAAA__8%3D&layout=dagre&sketch=0&theme=0&

I think for this we would need the following:

1. Right angled connections (sharp edge connection)
2. As a starting point, basic analog icons - see https://www.ultralibrarian.com/2020/11/24/electronic-component-lists-and-schematic-symbols-ulc
3. Labels that can be put outside of the icon

Digital icons can be added later once you have a proof of concept

**Comment by alixander** [comment]
https://play.d2lang.com/?script=RJLBbsMgEETv-xVzyi0GnKaSV3L7EVU_wLFRYtUGBCRRVfnfK5Y0Pa1mDsvyZp7xMmLBSfRoAeOHgGjTnLKPVQFCgTGvw9mKUUNgHLRI2cl4raqkwbjkHBIrdWqP7eFF6yat13QZJ9eMflUPU93DfvQuW5fVNSx-mJJqdauVMUpeM10T3Pl98Sl992aXcpxDb3Z3ewq9IWCjjejzox4qDP9uLsVjCJ4wROty_cl_HIxWFgDdDfs3HI76q8zFTmV0N4J4jaDhJxTa6DcAAP__&layout=tala&sketch=0&theme=0&

it's pretty close. this type of diagram cannot be done in elk or dagre btw, because they only do hierarchical diagrams.

i think implementing ports is all that's needed: https://github.com/terrastruct/d2/issues/628

**Comment by akshaybabloo** [comment]
Not that I know of @alixander

**Comment by akshaybabloo** [comment]
Also, the ends are not really connected to the resistor there, it's just hovering. It would be nice to have some internal icons that can do that.

**Comment by alixander** [comment]
just need ports (can then specify to only route through the left and right sides of the icon)

**Comment by BarryNolte** [comment]
Tools to create schematics, off the top of my head:

1. KiCad
2. OrCad
3. Altium
4. Proteus
5. Fusion 360
6. CircuitMaker.com

**Comment by alixander** [comment]
can you generate with text in any of these? @BarryNolte

**Comment by BarryNolte** [comment]
I think what you want is a 'net list'. https://en.wikipedia.org/wiki/Netlist.  They all probably produce a net list; some might read them.  I don't think it's a super well-defined standard, otherwise there wouldn't be a lot of discussion on converting files from one EDA package to another, which is the evergreen topic on electronics message boards.

**Comment by akshaybabloo** [comment]
Most of them use a combination of XML and binary

**Comment by alixander** [comment]
sorry i meant are any of these tools text-to-circuit-diagram. not whether they can export to text.

could be a good opportunity to expand d2 with no much more extra work if a comparable solution doesn't exist yet and there's demand for it

**Comment by BarryNolte** [comment]
I think there are some netlist -> html/svg projects around.

**Comment by alixander** [comment]
oh interesting, yeah: https://github.com/nturley/netlistsvg#examples

looks like they use ELK too.

**Comment by BarryNolte** [comment]
Yup, just found that one too.

**Comment by alixander** [comment]
that one seems quite good. i'm going to close this then as not something D2 should focus on.
