### ISSUE TITLE
Nesting imports failing

### ISSUE THREAD

**Issue by ErikEvenson** [terrastruct/d2#1407]
The following fails with
```
err: failed to compile: ./x/y/y.d2:3:2: linked board not found
err: ./x/y/y.d2:3:2: linked board not found
```

./root.d2:
```
x: X {
	link: layers.x
}

layers: {
	x: @x/x
}
```

./x/x.d2:
```
x: {
	...@y/y
	y.link: layers.y
}

layers: {
	y: @y/y
}
```

./x/y/y.d2:
```
y: {
	...@z/z
	z.link: layers.z
}

layers: {
	z: @z/z
}
```

./x/y/z/z.d2:
```
z
```

If I leave the final link off (`z.link: layers.z`) it compiles fine.

**Comment by alixander** [comment]
This is expected behavior.

In `x.d2`, you're importing a whole diagram of `y` into `x`, but since it is nested inside `x`, the `y`'s boards won't be nested into `x` since that doesn't make sense. So since `y`'s boards aren't imported over, `y`'s link to the layer `z` is no longer found.

You can get around this by pointing to layers you've imported instead.

So `x.d2` would be like

```d2
x: {
	y.link: layers.y
}

layers: {
	y: @y/y
}
```
