### ISSUE TITLE
Elk: use ports for columns in the sql table shape

### ISSUE THREAD

**Issue by janydoe** [terrastruct/d2#1429]
At the moment for the sql_table shape only TALA layout engine render connections to the exact columns.

But I think we could implement it for the ELK via "ports"

References:
- https://rtsys.informatik.uni-kiel.de/elklive/examples.html?e=general%2Fspacing%2Fports

**Comment by alixander** [comment]
yeah 100%, should be doable in ELK. (related: https://github.com/terrastruct/d2/issues/630#issuecomment-1376053367)

**Comment by landmaj** [comment]
I got it *somewhat* working. 

<img width="2329" alt="Screenshot 2023-10-14 at 22 15 05" src="https://github.com/terrastruct/d2/assets/13437951/1ab7e2a7-a8ad-4ce6-bd2f-4b0ff245d4f7">

It is not perfect and works differently than TALA, since all connections leave from the right side and enter on the left side. [There is a way to make ELK choose on which side a port should be placed](https://eclipse.dev/elk/reference/options/org-eclipse-elk-layered-allowNonFlowPortsToSwitchSides.html), but it only does it to reduce number of crossings, it doesn't care about connection length or aesthetics. And I don't know if it would even work, since I can't figure out how to set correct Y coordinate for ports when `portConstraints` is set to `FIXED_SIDE`.

Would you be interested in a PR if I can make it work reliably?

**Comment by alixander** [comment]
@landmaj What's the behavior when you connect sql table row to non-sql table thing? Or sql table row to just sql table.

I think the leaving and entering on consistent sides isn't entirely a negative to everyone, so I wouldn't say that's a blocker.

A PR would be welcome! ❤️

**Comment by landmaj** [comment]
For some reason when you connect sql table row to sql table, the arrow goes to the upper left corner. I have no idea why but I should be able to fix it. Connecting sql table row to non-sql table thing works just fine, no issues there.

I found another issue - there is a piece of code in `d2elklayout` [which tries to remove "ladders"](https://github.com/terrastruct/d2/commit/f35be526c6a0fa2778fd58f9469a8479d5a90a87). It sometimes breaks merging edges and it looks ugly. I guess it was never an issue because I don't think it is possible to have merging edges if you don't use ports?

With ladder removal code:
<img width="2170" alt="Screenshot 2023-10-15 at 19 13 42" src="https://github.com/terrastruct/d2/assets/13437951/72b89258-a670-40af-9fcf-b34bdcf20837">

Without ladder removal code:
<img width="2225" alt="Screenshot 2023-10-15 at 19 14 11" src="https://github.com/terrastruct/d2/assets/13437951/c11eda87-0dad-4ca1-920d-e1b2efbe2125">

And as you can see I figured out how to automatically choose left/right side. Thought I'm still not sure if implementing this feature, fixed sides or not, is actually worth it. The diagrams end up being much more spread out. 

Here you can see an example with all the bugs mentioned above:
<img width="2338" alt="Screenshot 2023-10-15 at 19 33 02" src="https://github.com/terrastruct/d2/assets/13437951/d432b8b6-14c5-4c94-86c8-ffc9f7b267d9">

Same diagram rendered using D2 v0.6.1:
<img width="1643" alt="Screenshot 2023-10-15 at 19 32 39" src="https://github.com/terrastruct/d2/assets/13437951/23bbd0a0-a384-4fb7-ac0e-f18439e9f9ea">

**Comment by alixander** [comment]
> I guess it was never an issue because I don't think it is possible to have merging edges if you don't use ports?

I think that's right, the code doesn't account for merges. That looks good! I think even if the routes are a little messier, it's entirely in the user's hands whether they want to activate it by specifying ports when declaring connections (assuming the "going to top left" bug gets fixed).

**Comment by landmaj** [comment]
OK, thanks for feedback. I will get back to work but it may take some time, since I have a real work too. 😆 I will be back with a fully working implementation next weekend, I hope.

**Comment by alixander** [comment]
Yup understand, thank you!

**Comment by landmaj** [comment]
I have a version I think I'm happy with. Let me know I you like it and I will add tests and create PR.

If connections leaving from rows have meaning, defining ports every X pixels around the border for table connections would be misleading. I settled on the following settings:
- incoming row connections: LEFT
- outgoing row connections: RIGHT
- incoming table connections: TOP
- outgoing table connections: BOTTOM

For `direction: up` table connections have switched sides, and for `direction: left` row connections are switched.

The end result looks good IMO.

```d2
primary: {
  shape: sql_table
  id: int {constraint: primary_key}
  primary_id: int {constraint: foreign_key}
  column: string
}

primary.primary_id -> primary.id
obj -> primary

secondary: {
  shape: sql_table
  id: int {constraint: primary_key}
  primary_id: int {constraint: foreign_key}
  column: string
}

secondary.primary_id -> primary.id
secondary -> obj
```

All table and column names are the same because I forgot to uncomment code which censored names from a real db (which I will show later).

## Down
![sql](https://github.com/terrastruct/d2/assets/13437951/edf0d910-8e09-4605-921f-e61c12ca65e6)

## Up
![sql](https://github.com/terrastruct/d2/assets/13437951/d17d7a82-6c6a-4163-8967-75d4dd5884f8)

## Right
![sql](https://github.com/terrastruct/d2/assets/13437951/4102268b-fef0-4b19-8cc4-83a94e1aa14b)

## Left
![sql](https://github.com/terrastruct/d2/assets/13437951/544d0963-b82c-4181-9ab0-f4e9dd227996)

**Comment by landmaj** [comment]
Real database
![sql](https://github.com/terrastruct/d2/assets/13437951/7cfcf3f0-91a7-4896-8569-a7c5a2799836)

One connection is misaligned if the direction is left or right. I have no idea why, I just noticed it.
![sql](https://github.com/terrastruct/d2/assets/13437951/cadb181e-7bb5-4ff2-90e7-d5b5eba87918)

I also tested it on a diagram from #1668. It looks messy but the diagram is insane.
![sql](https://github.com/terrastruct/d2/assets/13437951/5eebd714-7b19-46f1-a119-76098821513c)
If you look at the bottom connection, it is not centered correctly. I think ELK moved my port for some reason.

**Comment by alixander** [comment]
Wow, nice work! 

> If connections leaving from rows have meaning, defining ports every X pixels around the border for table connections would be misleading.

Right, agreed. 

------------

Note to self to recommend direction: right/left for ERDs that utilize this in ELK.

------------

i think the misalignments just come from hacks we do for padding on labels and containers. @gavin-ts can speak to this more. 

----------

![Screen Shot 2023-10-21 at 11 50 13 AM](https://github.com/terrastruct/d2/assets/3120367/1736bf83-9f6a-4d54-a5eb-521f9fcd8c11)


I wonder if the code made the red connection first, gave it the first available port (which goes clockwise), and then defined the green one next, leading to the crossover. In which case, a post-processing step of swapping ports to reduce crossings would be helpful.

------------

> Let me know I you like it and I will add tests and create PR.

Yes please!

**Comment by alixander** [comment]
![Screen Shot 2023-10-21 at 11 53 22 AM](https://github.com/terrastruct/d2/assets/3120367/d91a3795-a027-4bcc-a061-23a010ab89a9)

In that last diagram, the laddering code would've helped. I wonder why it didn't kick in here, they're not sharing a route.

**Comment by landmaj** [comment]
<img width="314" alt="Screenshot 2023-10-21 at 20 59 57" src="https://github.com/terrastruct/d2/assets/13437951/e38dfcfa-cf27-4ae4-9cf2-32db7e660adc">

This is because I have to set fixed port positions and manually assign edges to ports, so they are in the order in which they were defined. I couldn't find a way to have both fixed ports on the sides and automatically placed on top/bottom.

I thought about creating an invisible node with the exact same dimentions inside the existing node. This way I could have `FIXED_POS` for one node and `FIXED_SIDE` for the other, so the top/bottom ports should be able to move during layout creation. It's just an idea, I don't know if it is even possible.

I will leave this issue for later, since connections to and from tables should not be that common if column connections work.

**Comment by landmaj** [comment]
> In that last diagram, the laddering code would've helped. I wonder why it didn't kick in here, they're not sharing a route.

It should work better now, before it skipped all row connections, even if they never merged anywhere. It now checks if "corner" point is shared with any other route, so even long, merging edges should be able to benefit from ladder removal.

I also fixed misaligned connections. Instead of checking if end point is still attached to a node, for row connections it checks if new Y coordinate is within 1/3 row height from the row center.

This is diagam from #1668 rendered using code from just opened PR. 
![sql](https://github.com/terrastruct/d2/assets/13437951/bf95f10d-1e7c-4381-a685-b8fd7d054403)

Some connections could look better but it's still better than without any straightening at all. Here is a version with all straightening logic disabled. The direction is changed because I apparently changed it yesterday and didn't notice before making a screenshot. The edges are identical, just mirrored.
<img width="213" alt="Screenshot 2023-10-22 at 11 27 29" src="https://github.com/terrastruct/d2/assets/13437951/b2b67921-3090-4255-b881-c436ca5690bb">

And here is my DB. Topmost connection is now properly connected.
![sql](https://github.com/terrastruct/d2/assets/13437951/6c99bf91-d082-4387-b3af-4dd8bf113a4b)

**Comment by landmaj** [comment]
The only issue left I can think of is when you specify diffrent arrowheads for multiple connections to a single row. Here is an example:
```d2
direction: right

a: {
    shape: sql_table
    id: int { constraint: primary_key }
}

b: {
    shape: sql_table
    id: int { constraint: primary_key }
    a_1: int { constraint: foreign_key }
    a_2: int { constraint: foreign_key }
}

b.a_1 -> a.id: {
    target-arrowhead.shape: cf-many
}
b.a_2 -> a.id
```

![sql](https://github.com/terrastruct/d2/assets/13437951/1aec06a8-26c0-4e46-911b-401d1edefc94)

They are overlaid on each other. But I don't think there is any way to make it work.

**Comment by landmaj** [comment]
BTW this issue was a fun challenge but I think you should reconsider `good first issue` label. 🤣
