### ISSUE TITLE
grid labels in TALA are offset

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#1569]
<img width="990" alt="Screen Shot 2023-08-30 at 4 17 26 AM" src="https://github.com/terrastruct/d2/assets/3120367/069bf751-9a42-4625-8abe-f2431428849b">

```d2
region: Region-guangzhou {
  icon: https://icons.terrastruct.com/aws%2F_Group%20Icons%2FRegion_light-bg.svg
  icon.near: top-left
  label.near: outside-top-left
  style: {
    stroke: blue
    fill: white
    font-color: blue
  }
  vpc: VPC {
    icon: https://icons.terrastruct.com/aws%2F_Group%20Icons%2FVirtual-private-cloud-VPC_light-bg.svg
    icon.near: top-left
    width: 400
    height: 500
    label.near: outside-top-left
    style: {
      stroke: green
      font-color: green
      fill: white
    }
    ip: 10.68.0.0/16 {
      label.near: outside-bottom-center
      style: {
        stroke-width: 1
        fill: white
      }
      nat1: {
        icon: https://icons.terrastruct.com/aws%2FNetworking%20&%20Content%20Delivery%2FAmazon-VPC_NAT-Gateway_light-bg.svg
        label.near: bottom-center
        icon.near: top-center
        style: {
          stroke-width: 1
        }
        nat: NAT {
          icon: https://icons.terrastruct.com/aws%2FNetworking%20&%20Content%20Delivery%2FAmazon-VPC_NAT-Gateway_light-bg.svg
          label.near: bottom-center
          style: {
            stroke-width: 1
          }
        }
        az5: Availability Zone 5 {
          style: {
            stroke: blue
            font-color: blue
            stroke-dash: 3
            fill: white
          }
          grid-columns: 1

          master: Master Subnet {
            icon: https://icons.terrastruct.com/aws%2F_Group%20Icons%2FVPC-subnet-private_light-bg.svg
            icon.near: top-left
            label.near: outside-top-center
            ex: 10.68.8.0/23 {
              label.near: outside-bottom-center
              style: {
                stroke-width: 0
              }
            }
          }
          node-subnet5: Node Subnet {
            icon: https://icons.terrastruct.com/aws%2F_Group%20Icons%2FVPC-subnet-private_light-bg.svg
            icon.near: top-left
            label.near: outside-top-center
            style: {
              stroke: purple
              font-color: purple
              fill: white
            }
            xx: 10.68.12.0/23 {
              label.near: outside-bottom-center
              style: {
                stroke-width: 0
              }
            }
          }
          pod-subnet5: Pod Subnet {
            icon: https://icons.terrastruct.com/aws%2F_Group%20Icons%2FVPC-subnet-private_light-bg.svg
            icon.near: top-left
            label.near: outside-top-center
            style: {
              stroke: purple
              font-color: purple
              fill: white
            }
            xx: 10.68.64.0/20 {
              label.near: outside-bottom-center
              style: {
                stroke-width: 0
              }
            }
          }
          # master -> node-subnet5 -> pod-subnet5: {
          #   style: {
          #     opacity: 0
          #   }
          # }
        }
        az5 -> nat
        # az5.master -> nat
        # az5.node-subnet5 -> nat
        # az5.pod-subnet5 -> nat

        az6: Availability Zone 6 {
          style: {
            stroke: blue
            font-color: blue
            stroke-dash: 3
            fill: white
          }
          grid-columns: 1
          node-subnet6: Node Subnet {
            icon: https://icons.terrastruct.com/aws%2F_Group%20Icons%2FVPC-subnet-private_light-bg.svg
            icon.near: top-left
            label.near: outside-top-center
            style: {
              stroke: purple
              font-color: purple
              fill: white
            }
            ex: 10.68.10.0/23 {
              label.near: outside-bottom-center
              style: {
                stroke-width: 0
              }
            }
          }
          pod-subnet6: pod Subnet {
            icon: https://icons.terrastruct.com/aws%2F_Group%20Icons%2FVPC-subnet-private_light-bg.svg
            icon.near: top-left
            label.near: outside-top-center
            style: {
              stroke: purple
              font-color: purple
              fill: white
            }
            ex: 10.68.64.0/20 {
              label.near: outside-bottom-center
              style: {
                stroke-width: 0
              }
            }
          }
          # node-subnet6 -- pod-subnet6: {
          #   style: {
          #     # opacity: 0
          #   }
          # }
        }
        az6 -> nat
        # az6.node-subnet6 -> nat
        # az6.pod-subnet6 -> nat
      }
    }
  }
}

```

**Comment by gavin-ts** [comment]
Looking into this, the offset exists because the font size is inconsistent with the label dimensions. When TALA changes the font size, the label dimensions aren't updated, and so the rendered position is inconsistent with the font size (bug 1). The other issue here is that inside the grid, the nested tala layout sees the containers as being level 1 and so font size is set to 28, when in reality it is level > 3 so it should have font size 16 (bug 2). 

If we just fixed bug 2 tala would no longer incorrectly set the font size to 28, and this example would be fixed, but to fix scenarios where TALA does and should adjust the font size, we also need to fix bug 1. If we only fix bug 1, it would also fix the offset in this example, but the font-size would still incorrectly be 28.

Setting `style.font-size: 16` shows what the correct render should look like:

<img width="926" alt="Screen Shot 2023-09-01 at 6 23 48 PM" src="https://github.com/terrastruct/d2/assets/85081687/0ea78ba7-2550-481d-bc7e-d043d0a5234b">

https://play.d2lang.com/?script=7FhNa-M8EL7nVwwEvzc5stuYosMLIUvLHjaE3dLDXoqSCNesIxlZTpqW_PdFij8kf-wGCt0N2x4aj2YsPfPMo5k2ksWJ4AS-mk8UF5THL0-igNcRgM6OwJNSWU4mE23lvmJS0lzJYq38tdhO6D73wtvHOymKzAvxZx3khben_R5TTRlaxX6-i8sNfU0HASUypIkaARjqymVRqDzZMGS5TbbEANKGpoHAKi2YWdD1JLB_SlRp11Wtg44jgF22JvCwnJfbvCGzh0SqgqYok8mOKobWqSg26GE5byc7lC6AYZ7ANcbGPAmLwLS0f8NHi5GGk1gyxss1mwZnvUXX8QQ0IxBgP7rxsY8nQVRv3QdlJZQSW7RmXDFZQ3AQVZhQmWlQr7fPrxAAcKoCe4fzS7Rgai_kj4THXoj_80I8F1wxrrwQf2JpsmPy4IW3sy19EdwUajG7R3dUsT09dIvWTrsv3U5pW94OHcOEHOsnThWBxezeee1PsnAOD725Dmdr59s80ZcpgdmOJildJWmiDvBdcAbTFoGD51jtoNZZtw100Om2SuDKfa-jTxcqgD0jdGqWa0tzxSSBL-YTvhUrzlQH8SFlfj1xCASR439LZ1rOUW7OrJrTUF2HW1P1M9SDOuUHYM9V87jx8SS8aiV8fhP5ZaWhoyrc8h9HQ5b9zMWGlSxNCSzEhv0rdRqgtbpCWSGzlLWc9jXqD-i9L-1iPNcSCcIL0EgmNo1ElmLzoZB3VEh0rRWC_26FjMteD-h_p6No21HPq_NSL6qx-V3-g-ACGneOHRifBgdtCj_Wi76FseNro-5GWHlUAdaRUd_Eji5iYjcei4ToYxi801Vv_l4I8EUNg4ho40Mh76iQCxkGdh8BhFzNnD0Cxm8bAlFfG498F1tfhIXWDTjtfjRfoRxHPwMAAP__&layout=tala&

See https://github.com/terrastruct/d2/blob/master/d2graph/d2graph.go#L425

**Comment by alixander** [comment]
> but to fix scenarios where TALA does and should adjust the font size, we also need to fix bug 1

@gavin-ts why is that?

**Comment by gavin-ts** [comment]
> When TALA changes the font size, the label dimensions aren't updated, and so the rendered position is inconsistent with the font size (bug 1).

The rendered label position will be incorrect since we use `d2target.Shape.LabelWidth` and `LabelHeight` for rendering,

https://github.com/terrastruct/d2/blob/dd131f83adb297c8b9b00728b410505b9c52f6ff/d2renderers/d2svg/d2svg.go#L1342
 
and these values come from `Object.LabelDimensions` which is calculated *before layout* with the `Object.Text()` font size. 

https://github.com/terrastruct/d2/blob/dd131f83adb297c8b9b00728b410505b9c52f6ff/d2graph/d2graph.go#L888

So the bug is when we update the font size during layout (and that adjusts the rendered font size correctly) but the rendered position isn't correct.

Bug 2 is simply that there shouldn't actually be a different font size in this scenario, but it thinks the shape is at the outermost level when it is in fact nested.

**Comment by gavin-ts** [comment]
> When TALA changes the font size, the label dimensions aren't updated, and so the rendered position is inconsistent with the font size (bug 1).

It turns out that we already do adjust the label dimensions when we adjust the font size in TALA, so bug1 didn't actually exist. The problem was only that the font size was unexpectedly being changed due to the incorrect object Level. When we intentionally change the font size in TALA we also update the dimensions.
