### ISSUE TITLE
investigate flaky daily CI

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#1682]
https://github.com/terrastruct/d2/actions/workflows/daily.yml

**Comment by gavin-ts** [comment]
Looks like it found a race condition when running two tests at once (`WARNING: DATA RACE`)

<img width="635" alt="Screenshot 2023-10-24 at 2 59 10 PM" src="https://github.com/terrastruct/d2/assets/85081687/59a432ce-9b91-4e3e-ad6c-ade8f3d2ed5a">

The race is between one test reading from `d2fonts.FontEncodings` when another is writing to it when adding a custom font.

The issue is that d2fonts.FontEncodings is global, but the `TestCLI_E2E` tests aren't really running copies of d2 in their own process, but it creates goroutines from the same process.

I don't think this is actually an issue when each d2 runs on its own, but a consequence of the test setup. We can fix it or disable this test when running with `--race`

**Comment by alixander** [comment]
ah right. Should we just wrap a mutex around it?

**Comment by gavin-ts** [comment]
> ah right. Should we just wrap a mutex around it?

I think we can change it from a Map to a `sync.Map` and it will handle the mutex for us
