### ISSUE TITLE
Local icons are not resolved correctly by cli

### ISSUE THREAD

**Issue by miroslav-matejovsky** [terrastruct/d2#1919]
When diagram is located in subfolder then relative path to icon location is not resolved correctly. Or at least not in the same way as it is by VSCode extension.

Repo with example: https://github.com/miroslav-matejovsky/d2-local-icons

**Comment by alixander** [comment]
Right, this is because the images are just URL paths. It depends on where you open the SVG. For example, in your repo, GitHub renders it: https://github.com/miroslav-matejovsky/d2-local-icons/blob/trunk/cli-output-conf.svg

But in others that won't make network requests like, say, Adobe Illustrator, you need to bundle the images into base64 data. D2 playground doesn't do that right now: https://github.com/terrastruct/d2-playground/issues/17

**Comment by miroslav-matejovsky** [comment]
Thanks, if someone is using [filewatcher](https://marketplace.visualstudio.com/items?itemName=appulate.filewatcher) to generate svg in vscode this (`cd` to folder with d2 definition) will help:

```
  "D2.previewTheme": "Cool classics",
  "filewatcher.commands": [
    {
      "match": "^.*\\.d2$",
      "isAsync": true,
      "cmd": "cd ${fileDirname} && d2 --layout tala --theme=4 ${file}
      "event": "onFileChange"
    }
  ],
```

**Comment by alixander** [comment]
Wait I'm sorry this wasn't in regards to the Playground. I mistook this for a different issue.

> When diagram is located in subfolder then relative path to icon location is not resolved correctly.

They both seems to have the correct icon in your repo. What's the issue? @miro

**Comment by miroslav-matejovsky** [comment]
I've update README.md in my repo.

https://github.com/miroslav-matejovsky/d2-local-icons/blob/trunk/cli-output-conf.svg is incorrect, it should contain gear instead of eye.

**Comment by alixander** [comment]
Very much appreciate the detailed bug report. Fix will be part of next release, thanks again.
