### ISSUE TITLE
Extra padding bug

### ISSUE THREAD

**Issue by jatolentino** [terrastruct/d2#1974]
Hello, I'm not sure if this is an issue related to the language itself but I found a weird bug. Whenever I add a new component, I get the first one with a different gap, although the class of this component stablishes that it doesn't have a gap.

For instance, in this script I have only the component `Backend Node`, whose class is `node` that styles the component with 0 gap. Everything cool there.

```
classes: {
  kuber: {
    style: {
      fill: "white"
      stroke: "#aeb5bd"
      border-radius: 4
      stroke-dash: 3
    }
  }
  sys: {
    label: ""
    style: {
      fill: "#AFBFDF"
      stroke: "#aeb5bd"
    }
  }
  node: {
    grid-gap: 0
    style: {
      fill: "#ebf3e6"
      border-radius: 8
      stroke: "#aeb5bd"
    }
  }
  clust: {
    style: {
      fill: "#A7CC9E"
      stroke: "#aeb5bd"
    }
  }
  deploy: {
    grid-gap: 0
    style: {
      fill: "#ffe6d5"
      stroke: "#aeb5bd"
      # border-radius: 4
    }
  }
  nextpod: {
    icon: https://www.svgrepo.com/show/378440/nextjs-fill.svg
    style: {
      fill: "#ECECEC"
      stroke: "#aeb5bd"
      # border-radius: 4
    }
  }
  flaskpod: {
    icon: https://www.svgrepo.com/show/508915/flask.svg
    style: {
      fill: "#ECECEC"
      stroke: "#aeb5bd"
      # border-radius: 4
    }
  }
}

classes

Kubernetes: {
  grid-columns: 2
  system: {
    grid-columns: 1
    Backend Node: {
      grid-columns: 2
      ClusterIP\nService 1
      Deployment 1: {
        grid-rows: 3
        NEXT POD 1
        NEXT POD 2
        NEXT POD 3
      }
    }
  }
}

kubernetes.class: kuber
kubernetes.system.class: sys

kubernetes.system.backend node.class: node
kubernetes.system.backend node.clusterip\nservice 1.class: clust
kubernetes.system.backend node.deployment 1.class: deploy
kubernetes.system.backend node.deployment 1.next pod*.class: nextpod
``` 

![d2-onecomponent](https://github.com/terrastruct/d2/assets/61167951/681bc24c-d0be-40d5-80ce-03a494069e64)

The problem occurs, when I add a second component, for example, a node called backend with the class `node` again. I don't understand why the first component gets a weird gap in the right side when its class specifies that there are no gaps.

```
classes: {
  kuber: {
    style: {
      fill: "white"
      stroke: "#aeb5bd"
      border-radius: 4
      stroke-dash: 3
    }
  }
  sys: {
    label: ""
    style: {
      fill: "#AFBFDF"
      stroke: "#aeb5bd"
    }
  }
  node: {
    grid-gap: 0
    style: {
      fill: "#ebf3e6"
      border-radius: 8
      stroke: "#aeb5bd"
    }
  }
  clust: {
    style: {
      fill: "#A7CC9E"
      stroke: "#aeb5bd"
    }
  }
  deploy: {
    grid-gap: 0
    style: {
      fill: "#ffe6d5"
      stroke: "#aeb5bd"
      # border-radius: 4
    }
  }
  nextpod: {
    icon: https://www.svgrepo.com/show/378440/nextjs-fill.svg
    style: {
      fill: "#ECECEC"
      stroke: "#aeb5bd"
      # border-radius: 4
    }
  }
  flaskpod: {
    icon: https://www.svgrepo.com/show/508915/flask.svg
    style: {
      fill: "#ECECEC"
      stroke: "#aeb5bd"
      # border-radius: 4
    }
  }
}

classes

Kubernetes: {
  grid-columns: 2
  system: {
    grid-columns: 1
    Backend Node: {
      grid-columns: 2
      ClusterIP\nService 1
      Deployment 1: {
        grid-rows: 3
        NEXT POD 1
        NEXT POD 2
        NEXT POD 3
      }
    }
    Frontend Node: {
      grid-columns: 2
      ClusterIP\nService 2
      Deployment 2: {
        grid-rows: 3
        FLASK POD 1
        FLASK POD 2
        FLASK POD 3
      }
    }
  }
}

kubernetes.class: kuber
kubernetes.system.class: sys

kubernetes.system.backend node.class: node
kubernetes.system.backend node.clusterip\nservice 1.class: clust
kubernetes.system.backend node.deployment 1.class: deploy
kubernetes.system.backend node.deployment 1.next pod*.class: nextpod

kubernetes.system.frontend node.class: node
kubernetes.system.frontend node.clusterip\nservice 2.class: clust
kubernetes.system.frontend node.deployment 2.class: deploy
kubernetes.system.frontend node.deployment 2.flask pod*.class: flaskpod

```

![d2-twocomponents](https://github.com/terrastruct/d2/assets/61167951/54a844ef-d183-425f-a72b-c72fdc4e5e7c)

**Comment by alixander** [comment]
hm so this happens because the outer `grid-columns: 1` will make each container the same width.

e.g.

```d2
x: {
  grid-columns: 1

  aljksadf
  b
}
```

<img width="293" alt="Screenshot 2024-09-16 at 9 24 38 AM" src="https://github.com/user-attachments/assets/e56058d9-0945-4fdc-b232-695e9fe471ce">

This is what is expected from grids.

------------

In your case, "Flask pod 1" was a little wider than "Next pod 1" due to more chars. If you specify their widths to be the same, you'll get the width elements.

<img width="281" alt="Screenshot 2024-09-16 at 9 26 16 AM" src="https://github.com/user-attachments/assets/cbb39a99-e2d3-4037-a37a-2e10c456bb85">

https://play.d2lang.com/?script=vFRNb9pAEL37V4zgVgkMBhKyN8KHVKVKI6WHHnKxvWNwMV5rZ4mLKv57tWvWQHBtIqQagczbmbdv9u1MmPhESAz-OADrbYCyeAUgtUvQ_gGI4iRh0MpXscLWASMlxRoZtNo-BqOAWzwQkqPsSJ_HW2IwPAvvcJ9WDAYG3DvFl3Zkt0r8APVOrRoV7cnicTFb1Ouw3KngJcNSxryz9DMGvTp6DKIB3v2jnPFVu4bJllT9WbYn99Ppw_y6Kjhmidh9so4owjs-arKrXW1YeX74W2WCW_Y85mrFoD8udo5DkTJYKZURc908z7v0vpSYiW4oNi6tRO4O7sfDYc_VPL-oo7XpmDrd86n-3Kg7Snxa3yR81Bs_9EeuIfoPkveOc2hHx3nSrZiisq1pDA9Fst2kxMArWkbh5uxClOt9gz364RpTDs8nDVDFpJ-pvq4ov768pa8o3-MQDyQAM3PzNpgq6B9pDkRS5GSbWT_P858_4OX7rMw-gbxLyCbunePvQopU3aDbu9TtNepefJu8Pn0QfsS8CuxSunFwXRrXNWayYqqe4oVzdpl25FSsBgfz9PSyofq9OdQcSJy9pWSNtPlmrYmAn9htEwvsU5m62yET_EspvhgjVbVG1vEriv0Ye1Gt11TtOcOJaK-x3JpUMyTOCrbzx_kbAAD__w%3D%3D&

-------

This is a good learning example. May I include it in our documentation site in a FAQ section on grids? @jatolentino

**Comment by jatolentino** [comment]
@alixander Thanks for the explanation! Sure do it please, I'll be looking forward to read the docs!
