### ISSUE TITLE
Unknown error. Not sure what is going on as there is no meaningful error message

### ISSUE THREAD

**Issue by BryanNsoh** [terrastruct/d2#2229]
https://play.d2lang.com/?script=rM7BS8MwFMfxe_6KHxM8uRE3u0HAk3jwXMGD9ZC2bzX4mo68FpWt_7s0taMnETS3fB8v-VTBlcui4a72YrBR8V7Zg0GilSrYipAYHBVQk5UuUE2-HQMgr_ZABoGK1vqKaYztJ9NK2tC8kcHiYp1sN5QvZrO9Yx4m-3jmk7wJJYVlsKXrxOBGAb3qlaLvLyPIzCkKYJsTG5zYtvQRH8tyqpw_WnaVp7KP7f4Rl7fYrXSGukaWnWPmPJ71Fdb6ZVwmX85XTwOgeBf3Z8LdU_owIPQq0ZNgbJPh-geC_AchPRN224mQ_pbwFQAA__8%3D&layout=dagre&

**Comment by alixander** [comment]
Ah, yeah the error message is lacking. This one is due to requiring double escapes in latex (https://d2lang.com/tour/text/#latex):

https://play.d2lang.com/?script=rM7BS8MwFMfxe_6KHxM8uRI3u0HAk3jwXMGD8ZC2bzWYpiOvRWXr_y5NR9eTCC63fB95-VTBlsuicV3tWWEt4r0ye4VUClE4w0yscBBATYa7QDX5dgwAv5s9KQQqWuMrR2Nsvx0l3IbmgxQWV6t0s6Z8MZvtrHPDZBfPfJI3oaSwDKa0HSvcCaAXvRB0-jKC1JwiAGdycgpHZ1r6isu0zqmy_mCcrTyVfYyPz7i-xzaRGnUNrbWestbW41XeYCXfTgvIl_Pnx0FRfLL9v-PhJXsaJDJJ5Zkx1gly-5uDL-LIJsd2c3Zkf3f8BAAA__8%3D&layout=dagre&

**Comment by alixander** [comment]
This will change in the next release
