### ISSUE TITLE
Adding line break and more efficient spacing

### ISSUE THREAD

**Issue by kangruixiang** [terrastruct/d2#479]
Hi, I have this diagram I made in Microsoft Publisher that I'm trying to move away from. 

![image](https://user-images.githubusercontent.com/17035138/208697895-c95ef7fd-e7f4-4124-b08c-d1084a4f4787.png)

There are two things I could not figure out how to make: 
1. line break within the text boxes. If I use | for block text, the style goes away
2. the connections to the right side of the main top-bottom flow

It ends up looking something like this, which is very not space efficient.
![image](https://user-images.githubusercontent.com/17035138/208698892-f39cc91a-53cd-4851-bb82-d6fd10968f25.png)

**Comment by murphyke** [comment]
@kangruixiang Did you figure out your issues?

For issue 1, instead of using the block text syntax (line breaks), you can insert newline characters like this:

```
initial-screen: Initial Screen\n(n = 8,910)
initial-screen.style.stroke: red
```

For issue 2 (layout), have you tried the `elk` layout engine (`d2 -l elk ...`)? If d2 keeps up with updates to the `dagre` (default) and `elk` layout engines, it might be worth trying with the latest version of d2 to see if there is any improvement.

There is also the option of paying Terrastruct to be able to use their proprietary `tala` layout, which is undeniably superior for certain diagrams. You can try `tala` out for free to see what it can do, but the resulting diagram will be watermarked.
