### ISSUE TITLE
animate keyword for bidirectional connections

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#654]
right now the bidirectional connections (arrowheads on both ends) just animate from source to target. It might be cool to add an invisible element in the middle of the connection and then animate in opposite directions.

![sketch exp (10)](https://user-images.githubusercontent.com/3120367/212159821-aa7ce4fc-286b-4fee-b3f6-ffdb0a188ea6.svg)

<img width="664" alt="Screen Shot 2023-01-12 at 2 25 56 PM" src="https://user-images.githubusercontent.com/3120367/212194151-065bf465-010f-48e1-9496-bb5cd8b89f0e.png">

**Comment by bo-ku-ra** [comment]
scrolling;
<-> : From the center to each end ■<<<<<>>>>>■ (direction of each arrow)
-- : From each end to the center 　■>>>>><<<<<■ (handshake image)

if it's one way, i have a problem maybe.
i want to make it right or down direction scrolling by design, not as semantics.
when editing, top and bottom, right and left are switched frequently.

**Comment by alixander** [comment]
i don't understand what you mean by scrolling, or handshake, or top/bottom

**Comment by bo-ku-ra** [comment]
https://github.com/terrastruct/d2/issues/1936#issuecomment-2103588340
