### ISSUE TITLE
resizing script makes SVGs un-embeddable

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#659]
To get interactivity for SVGs within web pages, you need <object> embed. When you use <object> embed, it's a separate document model created for the SVG. So the script in the SVG thinks its root and tries to resize incorrectly.

we should make it an opt-in flag

**Comment by alixander** [comment]
fyi @nhooyr

**Comment by nhooyr** [comment]
Does it think that the whole web page is its width/height? If so, why don't we just change it to use the root element width/height? Then that should work fine even if embedded.

**Comment by alixander** [comment]
no it thinks its containing element is. i set <object width="100%"... and it turned out like

<img width="1276" alt="Screen Shot 2023-01-13 at 12 26 22 PM" src="https://user-images.githubusercontent.com/3120367/212412984-2f059975-78da-472c-9f57-0aebe7b2eddb.png">

but actually i realized i can just set height and it works.

nvm then, we should just make a note of it in our docs, like in the troubleshooting section

**Comment by homeworkprod** [comment]
Is the embedded resize script really necessary at all? I was actually very surprised to find it in the SVG output.

IIRC, specifying `viewBox` but not `width` and `height` on an SVG makes it auto-scale in current browsers while preserving aspect ratio. Constraints can then be applied to its container (`<object>`, `<img>`, wrapper `<div>`, etc.) as necessary.

This article seems to cover it quite well: https://css-tricks.com/scale-svg/

**Comment by alixander** [comment]
it's a long article, can you reference the part where it says it auto-scales to fit to browser?

The use case here is giving users a pleasant experience when they open the SVG file standalone in the browser. AFAIK, without a script, there's no behavior where it auto-fits.

**Comment by homeworkprod** [comment]
> it's a long article, can you reference the part where it says it auto-scales to fit to browser?

The last paragraph of https://css-tricks.com/scale-svg/#aa-the-height-and-width-attributes mostly sums it up for me.

However, there'll probably still be cases this won't fully solve. It's a complicated mess, even if we don't have to care for MSIE anymore.

> The use case here is giving users a pleasant experience when they open the SVG file standalone in the browser. AFAIK, without a script, there's no behavior where it auto-fits.

I see. Yeah, that's my experience as well, unfortunately. And in addition, at least Firefox's zoom functionality doesn't work for me with standalone SVGs.


For my use case, which is replacing Graphviz-rendered images in Sphinx-generated documentation, I went with manually `d2`-compiled (and `pngquant`ed) PNGs instead of SVGs for now – primarly because of the SVG size (~800k SVG vs. ~20k PNG; can _maybe_ be somewhat mitigated by fixing #667, though), and the inline JavaScript doesn't really help in that regard.

**Comment by alixander** [comment]
Sans images, the output size is disproportionately a result of embedding fonts.

Unfortunately, `bundle` doesn't control that. There's 2 things that'll help with this:

1. Only embed glyphs used (e.g. if the letter "z" never appears in your labels, it won't loaded) https://github.com/terrastruct/d2/issues/638
2. Do not embed fonts. https://github.com/terrastruct/d2/discussions/132

**Comment by Vaelatern** [comment]
I'm finding that this nice snippet of CSS mostly helps

https://github.com/Vaelatern/mdbook-d2-go/blob/master/README.md#keeping-svgs-skinny

The fun problem I have is trying to put multiple embedded d2 svgs on a single page. So far my workaround is "a different page for each graph"
