### ISSUE TITLE
straying connector (dagre)

### ISSUE THREAD

**Issue by bo-ku-ra** [terrastruct/d2#707]
https://play.d2lang.com/?layout=dagre&script=PMyxDYBADAPA3lN4ASI7333BOhRIMAD63RF5oEoucuzOC2RiwJFcVjqy89zhQuexAXpjyjlJNZADA3IoQ-1Jf3v9F_5r9cjThTsAAP__&

**Comment by gavin-ts** [comment]
#646 #71

**Comment by gavin-ts** [comment]
this is related to a limitation with dagre as it doesn't support edges to containers. We work around that by routing to the container's descendant, and cutting the edge at the container border but this only helps for when the edge is connected to something outside the container. container self edges never exit the container (since dagre only can route child to child), and child - container edges also end up as child to child with dagre. #71 will track this until a solution is found

**Comment by bo-ku-ra** [comment]
if this problem occurs on d2(dagre), d2 should be abend (svg file is not output) and report this problem to me.
I will revise this d2 source.
