### ISSUE TITLE
Success message comes through stderr

### ISSUE THREAD

**Issue by BarryNolte** [terrastruct/d2#740]
When you run d2, and it completes successfully, the success message is printed out stderr instead of stdout.

Related: #541 

Configuration: Linux, but I haven't verified that it's isolated to Linux.

**Comment by bo-ku-ra** [comment]
i think 
```
d2 foo.d2 - > foo.svg
d2 foo.d2 - | perl
```
its message should out stderr.

**Comment by gavin-ts** [comment]
this is the expected behavior as I understand it (stdout=svg, stderr=logs) since stdout is reserved for writing the rendered SVG to as in @bo-ku-ra's examples where it is then redirected to a file or another program. I think we could change this if an output file is provided as an argument (since stdout wouldn't be used), but it would become inconsistent with other usage.
