### ISSUE TITLE
global styles

### ISSUE THREAD

**Issue by Morriz** [terrastruct/d2#909]
Please allow us to set global styles:
```yaml
style: {
  opacity: ...
}
```
Each context knows what is applicable and can start from global.

**Comment by alixander** [comment]
this won't work because styles will always be applicable to whatever scope is defining them. e.g. `style.fill` on root level should change the document background (not implemented yet), `style.fill` in a container will change that container's bg.

global styles (and global anything) will be set-able with globs:
https://github.com/terrastruct/d2/issues/103

**Comment by alixander** [comment]
closing for https://github.com/terrastruct/d2/issues/103

**Comment by Morriz** [comment]
> this won't work because styles will always be applicable to whatever scope is defining them. e.g. `style.fill` on root level should change the document background (not implemented yet: #663. i think i'll do it today though), `style.fill` in a container will change that container's bg.
> 
> global styles (and global anything) will be set-able with globs: #103

But that argument can be sidestepped with a reserved keyword:
```yaml
global: {
  shape: ...
  style: {
    opacity: ...
  }
}
```

and globs are surely not the same thing. Please re-think and re-open this.

**Comment by alixander** [comment]
what would `global` do differently than a recursive glob?

**Comment by Morriz** [comment]
ah, yes, I get it now...
