### ISSUE TITLE
trick of ”style”

### ISSUE THREAD

**Issue by bo-ku-ra** [terrastruct/d2#938]
https://play.d2lang.com/?l=&script=VJJBzoIwFIT3c4ohrGHxL7v4b2A8Q4EXbZRiaIka0rub1waFXfvSmW8yfdnFcAWpbRo-nL-BLDjDWYbvrcAN_34TTVkGh28yjPMiSEBNx956PmcXhZbB-ctdGuWzn8ZRfGyBF5t_voFdmvO1AnnS8g-vA5gNO8meUXylnJ2y5hKENmwKTksEaZXRqVoPg-GaNe22rSVzQsInAAD__w%3D%3D&

**Comment by alixander** [comment]
hah, so creative, love it.

i'll close this for now as it's not intended, and we should probably give an error so that users don't get confused why nothing is happening.

btw we do have multi-line comments right now. they're not documented though and comments may change before 1.0 anyway (to `//`)

https://play.d2lang.com/?l=&script=VJJBDoIwFET3c4oB1rBw2YU3MJ6hwI82SjG0RA3h7ua3QWXX_vx5M5k2UQwXkNqm4cP5G8hsZzhJ_71lc8PDb6Ip82D3TIZxmgUrUNGxs57PyUWhZXD-cpda_dmNwyA-NsCL9ZFvoCxLnK8FTtr5bilAKa0kUBRfpF38xa84B6ENm4LjHEFaRbcgOz30hkvSNNsnzVFXrPgEAAD__w%3D%3D&

**Comment by bo-ku-ra** [comment]
> (to `//`)

not as follows?
```
// single-line comment

/*
Multi-line
comments
*/
```

**Comment by alixander** [comment]
probably that too. some more discussion here: https://github.com/terrastruct/d2/discussions/905
