### ISSUE TITLE
Uncaught syntax error leads to bug in render

### ISSUE THREAD

**Issue by BarryNolte** [terrastruct/d2#955]
This;
```x <= y```

Leads to:

![image](https://user-images.githubusercontent.com/4474173/222462820-6570e0a2-caba-4129-b609-4522d7a32b9f.png)

Completes successfully, no errors.

**Comment by nhooyr** [comment]
None of these are syntax errors. This is completely expected behaviour and if you run `d2 fmt` on the input you'll see that the non edge syntax characters have a space added between them and the edge syntax.

So

```d2
x <= y
```

Becomes:

```d2
x <- = y
```

As expected. I understand it's confusing but that's why `d2` always formats your input files with `d2 fmt` when you compile too. To make it clear what's going on.
