### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#96]
just dealing with CGO

**Comment by alixander** [comment]
https://news.ycombinator.com/item?id=33711040

**Comment by nhooyr** [comment]
- [ ] build host
- [ ] terraauth update to support windows

In regards to the install script, idt it's worth adding a windows powershell/cmd.exe variant. Rather we add a https://chocolatey.org/ package instead.

**Comment by nhooyr** [comment]
Opened https://github.com/terrastruct/d2/issues/154

**Comment by alixander** [comment]
just adding another: https://news.ycombinator.com/item?id=33713748

**Comment by nhooyr** [comment]
https://news.ycombinator.com/item?id=33714812

we could have `install.sh` working under git bash for sure I think

**Comment by nhooyr** [comment]
For tomorrow's release, I'll most likely just build windows releases manually.

**Comment by nhooyr** [comment]
Damn, sorry guys it looks like v8go doesn't even support windows anymore :(

https://github.com/rogchap/v8go#windows

I'm going to try and work around it but will need more time.

**Comment by nhooyr** [comment]
Also see https://github.com/terrastruct/d2/issues/31.

I could try to compile v8 with emscripten to wasm and then run the JS with the wasm bundle under a go wasm runtime like https://github.com/wasmerio/wasmer-go (though it uses cgo it builds on windows). Or compiling the JS directly to wasm with something like https://github.com/Shopify/javy#build

And try out https://github.com/dop251/goja because with pure Go

As well as see if bundling the node binary is into our Go binary is feasible, then no cgo necessary.

**Comment by alixander** [comment]
@nhooyr i will give https://github.com/dop251/goja a try.

**Comment by alixander** [comment]
still working through some things but the fact it runs is promising. https://github.com/terrastruct/d2/pull/337

**Comment by alixander** [comment]
whether it can handle Mathjax's build will be the bigger question

**Comment by alixander** [comment]
good fucking find. v8go has been replaced with Goja. should be all good for full windows build

**Comment by nhooyr** [comment]
<img width="1680" alt="Screenshot 2022-12-06 at 2 55 27 AM" src="https://user-images.githubusercontent.com/10180857/205893146-bf2c33c3-d0c3-478e-bc0b-2d7e30b8b72e.png">

**Comment by nhooyr** [comment]
See https://github.com/terrastruct/d2/pull/378
